// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aserto-dev/azm/model/diff (interfaces: DirectoryValidator)

// Package diff is a generated GoMock package.
package diff

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockDirectoryValidator is a mock of DirectoryValidator interface
type MockDirectoryValidator struct {
	ctrl     *gomock.Controller
	recorder *MockDirectoryValidatorMockRecorder
}

// MockDirectoryValidatorMockRecorder is the mock recorder for MockDirectoryValidator
type MockDirectoryValidatorMockRecorder struct {
	mock *MockDirectoryValidator
}

// NewMockDirectoryValidator creates a new mock instance
func NewMockDirectoryValidator(ctrl *gomock.Controller) *MockDirectoryValidator {
	mock := &MockDirectoryValidator{ctrl: ctrl}
	mock.recorder = &MockDirectoryValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDirectoryValidator) EXPECT() *MockDirectoryValidatorMockRecorder {
	return m.recorder
}

// HasObjectInstances mocks base method
func (m *MockDirectoryValidator) HasObjectInstances(arg0 context.Context, arg1 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasObjectInstances", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasObjectInstances indicates an expected call of HasObjectInstances
func (mr *MockDirectoryValidatorMockRecorder) HasObjectInstances(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasObjectInstances", reflect.TypeOf((*MockDirectoryValidator)(nil).HasObjectInstances), arg0, arg1)
}

// HasRelationInstances mocks base method
func (m *MockDirectoryValidator) HasRelationInstances(arg0 context.Context, arg1, arg2 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasRelationInstances", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasRelationInstances indicates an expected call of HasRelationInstances
func (mr *MockDirectoryValidatorMockRecorder) HasRelationInstances(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasRelationInstances", reflect.TypeOf((*MockDirectoryValidator)(nil).HasRelationInstances), arg0, arg1, arg2)
}
